{
  File generated by GameHelper, tool provided with OGLCScene library.

  DON'T EDIT THIS UNIT because it may be overwritten by the tool -> your code will be lost !
  Instead, in another unit add "u_panel_baseoptions" in the uses clause
  and add your code in a class inherited from TPanelBaseOptions.

  Usage:
    - create an instance of the panel
      i.e. FBaseOptions := TCustomBaseOptions.Create(aLAYER_INDEX);
    or if the panel is a child of another surface:
           FBaseOptions := TCustomBaseOptions.Create(-1);
           FBaseOptions.SetChildOf(parentSurface, zordervalue);
    - initialize the panel coordinates
           FBaseOptions.Setcoordinates(...);
}

unit u_panel_baseoptions;

{$mode ObjFPC}{$H+}

interface

uses
  Classes, SysUtils,
  OGLCScene, BGRABitmap, BGRABitmapTypes, u_common;

type

TPanelBaseOptions = class(TUIModalPanel)
private
  class var texArrow: PTexture;
public
  BOK: TUIButton;
  RadioEasy: TUIRadio;
  RadioEasiest: TUIRadio;
  RadioNormal: TUIRadio;
  TextArea1: TUITextArea;
  CheckRetroMode: TUICheck;
  BUp: TUIButton;
  Label1: TUILabel;
  BLeft: TUIButton;
  LabelUp: TUILabel;
  LabelLeft: TUILabel;
  BRight: TUIButton;
  LabelRight: TUILabel;
  BDown: TUIButton;
  LabelDown: TUILabel;
  BPause: TUIButton;
  LabelPause: TUILabel;
  Label2: TUILabel;
  BResetHighScore: TUIButton;
  class procedure LoadTexture(aAtlas: TOGLCTextureAtlas);
  constructor Create;
end;

implementation

{ TPanelBaseOptions }

class procedure TPanelBaseOptions.LoadTexture(aAtlas: TOGLCTextureAtlas);
var texFolder: string;
begin
  texFolder := u_common.TexturesFolder;
  texArrow := aAtlas.RetrieveTextureByFileName('Arrow.svg');
  if texArrow = NIL then
    texArrow := aAtlas.AddFromSVG(texFolder+'Arrow.svg', ScaleW(32), ScaleH(32));
end;

constructor TPanelBaseOptions.Create;
begin
  inherited Create(FScene, 100);
  SetCoordinate(ScaleWF(47.96), ScaleHF(167.36));
  BodyShape.LoadFromString('ShapeType,1,RoundX,30.0000,RoundY,30.0000,Width,802,Height,761,FillData,Visible true Color 1E1E1EFF BlendMode 0,BorderData,Visible true Color DCDCDCFF Width 5.0000 BlendMode 0 LinePos 1');
  BodyShape.ResizeCurrentShape(ScaleW(802), ScaleH(761), True);

  BOK := TUIButton.Create(FScene);
  with BOK do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.412*Self.Width, 0.908*Self.Height);
    AutoSize := False;
    _Label.Tint.Value := BGRA(255,255,0);
    InitParameters('OK', texturedfontMenu, NIL);
    BodyShape.LoadFromString('ShapeType,1,RoundX,30.0000,RoundY,30.0000,Width,50,Height,24,FillData,Visible true Color 1E1D06FF BlendMode 0,BorderData,Visible true Color 918957FF Width 3.0000 BlendMode 0 LinePos 1');
    BodyShape.ResizeCurrentShape(ScaleW(149), ScaleH(50), True);
  end;

  RadioEasy := TUIRadio.Create(FScene, 'EASY', texturedfontText);
  with RadioEasy do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.397*Self.Width, 0.026*Self.Height);
    CustomizeCheckBox(ctCircle, cfColor);
    ColorChecked := BGRA(255,0,0);
    _Label.Tint.Value := BGRA(255,255,111);
  end;

  RadioEasiest := TUIRadio.Create(FScene, 'EASIEST', texturedfontText);
  with RadioEasiest do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.127*Self.Width, 0.026*Self.Height);
    CustomizeCheckBox(ctCircle, cfColor);
    ColorChecked := BGRA(255,0,0);
    _Label.Tint.Value := BGRA(255,255,111);
  end;

  RadioNormal := TUIRadio.Create(FScene, 'Normal', texturedfontText);
  with RadioNormal do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.725*Self.Width, 0.026*Self.Height);
    CustomizeCheckBox(ctCircle, cfColor);
    Checked := True;
    ColorChecked := BGRA(255,0,0);
    _Label.Tint.Value := BGRA(255,255,111);
  end;

  TextArea1 := TUITextArea.Create(FScene);
  with TextArea1 do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.001*Self.Width, 0.093*Self.Height);
    Pivot := PointF(0.50, 0.50);
    BodyShape.LoadFromString('ShapeType,0,Width,514,Height,100,FillData,Visible false,BorderData,Visible false Color DCDCDCFF Width 3.0000 BlendMode 0 LinePos 1');
    BodyShape.ResizeCurrentShape(ScaleW(792), ScaleH(77), True);
    Text.TexturedFont := texturedfontBonus;
    Text.Tint.Value := BGRA(220,220,220);
    Text.Caption := 'essai';
    Text.Align := taTopCenter;
  end;

  CheckRetroMode := TUICheck.Create(FScene, 'Apply pixel effect', texturedfontText);
  with CheckRetroMode do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.144*Self.Width, 0.195*Self.Height);
    CustomizeCheckBox(ctRectangle, cfCross);
    ColorChecked := BGRA(255,0,0);
    _Label.Tint.Value := BGRA(255,255,128);
  end;

  BUp := TUIButton.Create(FScene);
  with BUp do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.282*Self.Width, 0.464*Self.Height);
    _Label.Tint.Value := BGRA(0,0,0);
    InitParameters('', texturedfontText, texArrow);
    BodyShape.LoadFromString('ShapeType,1,RoundX,30.0000,RoundY,30.0000,Width,50,Height,37,FillData,Visible true Color FFFF00FF BlendMode 0,BorderData,Visible true Color DCDCDCFF Width 3.0000 BlendMode 0 LinePos 1');
    BodyShape.ResizeCurrentShape(ScaleW(45), ScaleH(42), True);
  end;

  Label1 := TUILabel.Create(FScene);
  with Label1 do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.037*Self.Width, 0.401*Self.Height);
    TexturedFont := texturedfontBonus;
    Caption := 'Click a button to redefine key';
  end;

  BLeft := TUIButton.Create(FScene);
  with BLeft do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.087*Self.Width, 0.598*Self.Height);
    _Label.Tint.Value := BGRA(0,0,0);
    InitParameters('', texturedfontText, texArrow);
    BodyShape.LoadFromString('ShapeType,1,RoundX,30.0000,RoundY,30.0000,Width,40,Height,40,FillData,Visible true Color FFFF00FF BlendMode 0,BorderData,Visible true Color DCDCDCFF Width 3.0000 BlendMode 0 LinePos 1');
    BodyShape.ResizeCurrentShape(ScaleW(45), ScaleH(42), True);
  end;

  LabelUp := TUILabel.Create(FScene);
  with LabelUp do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.287*Self.Width, 0.525*Self.Height);
    TexturedFont := texturedfontBonus;
    Caption := 'UP';
  end;

  LabelLeft := TUILabel.Create(FScene);
  with LabelLeft do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.078*Self.Width, 0.655*Self.Height);
    TexturedFont := texturedfontBonus;
    Caption := 'LEFT';
  end;

  BRight := TUIButton.Create(FScene);
  with BRight do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.463*Self.Width, 0.598*Self.Height);
    InitParameters('', texturedfontText, texArrow);
    BodyShape.LoadFromString('ShapeType,1,RoundX,30.0000,RoundY,30.0000,Width,40,Height,40,FillData,Visible true Color FFFF00FF BlendMode 0,BorderData,Visible true Color DCDCDCFF Width 3.0000 BlendMode 0 LinePos 1');
    BodyShape.ResizeCurrentShape(ScaleW(45), ScaleH(42), True);
  end;

  LabelRight := TUILabel.Create(FScene);
  with LabelRight do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.447*Self.Width, 0.652*Self.Height);
    TexturedFont := texturedfontBonus;
    Caption := 'RIGHT';
  end;

  BDown := TUIButton.Create(FScene);
  with BDown do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.282*Self.Width, 0.734*Self.Height);
    InitParameters('', texturedfontText, texArrow);
    BodyShape.LoadFromString('ShapeType,1,RoundX,30.0000,RoundY,30.0000,Width,40,Height,40,FillData,Visible true Color FFFF00FF BlendMode 0,BorderData,Visible true Color DCDCDCFF Width 3.0000 BlendMode 0 LinePos 1');
    BodyShape.ResizeCurrentShape(ScaleW(45), ScaleH(42), True);
  end;

  LabelDown := TUILabel.Create(FScene);
  with LabelDown do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.262*Self.Width, 0.792*Self.Height);
    Pivot := PointF(0.00, 0.00);
    TexturedFont := texturedfontBonus;
    Caption := 'DOWN';
  end;

  BPause := TUIButton.Create(FScene);
  with BPause do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.669*Self.Width, 0.472*Self.Height);
    _Label.Tint.Value := BGRA(0,0,0);
    InitParameters('PAUSE', texturedfontText, NIL);
    BodyShape.LoadFromString('ShapeType,1,RoundX,30.0000,RoundY,30.0000,Width,101,Height,40,FillData,Visible true Color FFFF00FF BlendMode 0,BorderData,Visible true Color DCDCDCFF Width 3.0000 BlendMode 0 LinePos 1');
    BodyShape.ResizeCurrentShape(ScaleW(95), ScaleH(42), True);
  end;

  LabelPause := TUILabel.Create(FScene);
  with LabelPause do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.672*Self.Width, 0.532*Self.Height);
    TexturedFont := texturedfontBonus;
    Caption := 'ESCAPE';
  end;

  Label2 := TUILabel.Create(FScene);
  with Label2 do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.037*Self.Width, 0.308*Self.Height);
    TexturedFont := texturedfontBonus;
    Caption := 'Current highscore: 0';
  end;

  BResetHighScore := TUIButton.Create(FScene);
  with BResetHighScore do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.622*Self.Width, 0.297*Self.Height);
    _Label.Tint.Value := BGRA(255,255,128);
    InitParameters('RESET HIGHSCORE', texturedfontText, NIL);
    BodyShape.LoadFromString('ShapeType,1,RoundX,30.0000,RoundY,30.0000,Width,150,Height,50,FillData,Color 1E1E1EFF BlendMode 0,BorderData,Color DCDCDCFF Width 3.0000 BlendMode 0 LinePos 1');
    BodyShape.ResizeCurrentShape(ScaleW(248), ScaleH(42), True);
  end;
end;

end.
