{
  File generated by GameHelper, tool provided with OGLCScene library.

  DON'T EDIT THIS UNIT because it may be overwritten by the tool -> your code will be lost !
  Instead, in another unit add "u_panel_basepause" in the uses clause
  and add your code in a class inherited from TPanelBasePause.

  Usage:
    - create an instance of the panel
      i.e. FBasePause := TCustomBasePause.Create(aLAYER_INDEX);
    or if the panel is a child of another surface:
           FBasePause := TCustomBasePause.Create(-1);
           FBasePause.SetChildOf(parentSurface, zordervalue);
    - initialize the panel coordinates
           FBasePause.Setcoordinates(...);
}

unit u_panel_basepause;

{$mode ObjFPC}{$H+}

interface

uses
  Classes, SysUtils,
  OGLCScene, BGRABitmap, BGRABitmapTypes, u_common;

type

TPanelBasePause = class(TUIModalPanel)
public
  Button1: TUIButton;
  Button2: TUIButton;
  constructor Create;
end;

implementation

{ TPanelBasePause }

constructor TPanelBasePause.Create;
begin
  inherited Create(FScene, 0);
  SetCoordinate(ScaleWF(267.16), ScaleHF(243.58));
  BodyShape.LoadFromString('ShapeType,1,RoundX,30.0000,RoundY,30.0000,Width,364,Height,191,FillData,Visible true Color 000000FF BlendMode 0,BorderData,Visible true Color FDF164FF Width 10.0000 BlendMode 0 LinePos 1');
  BodyShape.ResizeCurrentShape(ScaleW(364), ScaleH(191), True);

  Button1 := TUIButton.Create(FScene);
  with Button1 do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.203*Self.Width, 0.216*Self.Height);
    InitParameters('RESUME GAME', texturedfontText, NIL);
    BodyShape.LoadFromString('ShapeType,1,RoundX,30.0000,RoundY,30.0000,Width,218,Height,47,FillData,Visible true Color D08904FF BlendMode 0,BorderData,Visible true Color FDF164FF Width 5.0000 BlendMode 0 LinePos 1');
    BodyShape.ResizeCurrentShape(ScaleW(196), ScaleH(46), True);
  end;

  Button2 := TUIButton.Create(FScene);
  with Button2 do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.274*Self.Width, 0.588*Self.Height);
    InitParameters('MAIN MENU', texturedfontText, NIL);
    BodyShape.LoadFromString('ShapeType,1,RoundX,30.0000,RoundY,30.0000,Width,171,Height,41,FillData,Visible true Color D08904FF BlendMode 0,BorderData,Visible true Color FDF164FF Width 5.0000 BlendMode 0 LinePos 1');
    BodyShape.ResizeCurrentShape(ScaleW(164), ScaleH(46), True);
  end;
end;

end.
