{
  File generated by GameHelper, tool provided with OGLCScene library.

  DON'T EDIT THIS UNIT because it may be overwritten by the tool -> your code will be lost !
  Instead, in another unit add "u_panel_basepresskey" in the uses clause
  and add your code in a class inherited from TPanelBasePressKey.

  Usage:
    - create an instance of the panel
      i.e. FBasePressKey := TCustomBasePressKey.Create(aLAYER_INDEX);
    or if the panel is a child of another surface:
           FBasePressKey := TCustomBasePressKey.Create(-1);
           FBasePressKey.SetChildOf(parentSurface, zordervalue);
    - initialize the panel coordinates
           FBasePressKey.Setcoordinates(...);
}

unit u_panel_basepresskey;

{$mode ObjFPC}{$H+}

interface

uses
  Classes, SysUtils,
  OGLCScene, BGRABitmap, BGRABitmapTypes, u_common;

type

TPanelBasePressKey = class(TUIModalPanel)
public
  Label1: TUILabel;
  Label2: TUILabel;
  constructor Create;
end;

implementation

{ TPanelBasePressKey }

constructor TPanelBasePressKey.Create;
begin
  inherited Create(FScene, 100);
  SetCoordinate(ScaleWF(268.80), ScaleHF(658.49));
  BodyShape.LoadFromString('ShapeType,1,RoundX,30.0000,RoundY,30.0000,Width,802,Height,92,FillData,Visible true Color 1E0F07FF BlendMode 0,BorderData,Visible true Color DCDCDCFF Width 3.0000 BlendMode 0 LinePos 1');
  BodyShape.ResizeCurrentShape(ScaleW(408), ScaleH(92), True);

  Label1 := TUILabel.Create(FScene);
  with Label1 do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.297*Self.Width, 0.170*Self.Height);
    TexturedFont := texturedfontText;
    Caption := 'PRESS A KEY';
  end;

  Label2 := TUILabel.Create(FScene);
  with Label2 do begin
    SetChildOf(Self, 0);
    SetCoordinate(0.478*Self.Width, 0.536*Self.Height);
    TexturedFont := texturedfontText;
    Caption := '5';
  end;
end;

end.
