{
  File generated by GameHelper, tool provided with OGLCScene library.

  DON'T EDIT THIS UNIT because it may be overwritten by the tool -> your code will be lost !
  Instead, in another unit add "u_sprite_baseghost" in the uses clause
  and add your code in a class inherited from TBaseGhost.

  Usage:
    - add the sprite textures to your atlas with class method TBaseGhost.LoadTexture().
    - create an instance of the sprite
      i.e. FBaseGhost := TCustomBaseGhost.Create(aLAYER_INDEX);
    or if the sprite is a child of another:
           FBaseGhost := TCustomBaseGhost.Create(-1);
           FBaseGhost.SetChildOf(parentSprite, zordervalue);
    - initialize the sprite coordinates
           FBaseGhost.Setcoordinates(...);
}

unit u_sprite_baseghost;

{$mode ObjFPC}{$H+}

interface

uses
  Classes, SysUtils,
  OGLCScene, BGRABitmap, BGRABitmapTypes, u_common;

type

TBaseGhost = class(TSpriteContainer)
private
  class var texGhostBody, texGhostEyeDown, texGhostEyeLeft, texGhostEyeRight, texGhostEyeUp, 
  texGhostMouthEye, texGhostDressStretched, texGhostLeg, texGhostDressRepear: PTexture;
  class var FAdditionnalScale: single;
public
  GhostBody: TSprite;
  GhostEyeDown: TSprite;
  GhostEyeLeft: TSprite;
  GhostEyeRight: TSprite;
  GhostEyeUp: TSprite;
  GhostMouthEye: TSprite;
  DressStretched: TSprite;
  GhostLeg: TSprite;
  DressRepear: TSprite;
  class procedure LoadTexture(aAtlas: TOGLCTextureAtlas);
  constructor Create(aLayerIndex: integer=-1);
end;

implementation

{ TBaseGhost }

class procedure TBaseGhost.LoadTexture(aAtlas: TOGLCTextureAtlas);
var texFolder: string;
begin
  FAdditionnalScale := AdditionnalScale;
  texFolder := u_common.TexturesFolder;
  texGhostBody := aAtlas.RetrieveTextureByFileName('GhostBody.svg');
  if texGhostBody = NIL then
    texGhostBody := aAtlas.AddMultiFrameImageFromSVG(texFolder+'GhostBody.svg', ScaleW(64)*2, ScaleH(64)*1, 2, 1);
  texGhostEyeDown := aAtlas.RetrieveTextureByFileName('GhostEyeDown.svg');
  if texGhostEyeDown = NIL then
    texGhostEyeDown := aAtlas.AddFromSVG(texFolder+'GhostEyeDown.svg', ScaleW(39), ScaleH(19));
  texGhostEyeLeft := aAtlas.RetrieveTextureByFileName('GhostEyeLeft.svg');
  if texGhostEyeLeft = NIL then
    texGhostEyeLeft := aAtlas.AddFromSVG(texFolder+'GhostEyeLeft.svg', ScaleW(39), ScaleH(19));
  texGhostEyeRight := aAtlas.RetrieveTextureByFileName('GhostEyeRight.svg');
  if texGhostEyeRight = NIL then
    texGhostEyeRight := aAtlas.AddFromSVG(texFolder+'GhostEyeRight.svg', ScaleW(39), ScaleH(19));
  texGhostEyeUp := aAtlas.RetrieveTextureByFileName('GhostEyeUp.svg');
  if texGhostEyeUp = NIL then
    texGhostEyeUp := aAtlas.AddFromSVG(texFolder+'GhostEyeUp.svg', ScaleW(39), ScaleH(19));
  texGhostMouthEye := aAtlas.RetrieveTextureByFileName('GhostMouthEye.svg');
  if texGhostMouthEye = NIL then
    texGhostMouthEye := aAtlas.AddFromSVG(texFolder+'GhostMouthEye.svg', ScaleW(46), ScaleH(24));
  texGhostDressStretched := aAtlas.RetrieveTextureByFileName('GhostDressStretched.svg');
  if texGhostDressStretched = NIL then
    texGhostDressStretched := aAtlas.AddFromSVG(texFolder+'GhostDressStretched.svg', ScaleW(64), ScaleH(64));
  texGhostLeg := aAtlas.RetrieveTextureByFileName('GhostLeg.svg');
  if texGhostLeg = NIL then
    texGhostLeg := aAtlas.AddFromSVG(texFolder+'GhostLeg.svg', ScaleW(64), ScaleH(64));
  texGhostDressRepear := aAtlas.RetrieveTextureByFileName('GhostDressRepear.svg');
  if texGhostDressRepear = NIL then
    texGhostDressRepear := aAtlas.AddFromSVG(texFolder+'GhostDressRepear.svg', ScaleW(64), ScaleH(64));
end;

constructor TBaseGhost.Create(aLayerIndex: integer);
begin
  inherited Create(FScene);
  if aLayerIndex <> -1 then
    FScene.Add(Self, aLayerIndex);

  GhostBody := TSprite.Create(texGhostBody, False);
  with GhostBody do begin
    SetChildOf(Self, 0);
    Frame := 1.0;
    SetSize(ScaleW(Round(64*FAdditionnalScale)), ScaleH(Round(64*FAdditionnalScale)));
    SetCoordinate(ScaleWF(-32.000*FAdditionnalScale), ScaleHF(-32.000*FAdditionnalScale));
  end;

  GhostEyeDown := TSprite.Create(texGhostEyeDown, False);
  with GhostEyeDown do begin
    SetChildOf(Self, 1);
    Frame := 1.0;
    SetSize(ScaleW(Round(39*FAdditionnalScale)), ScaleH(Round(19*FAdditionnalScale)));
    SetCoordinate(ScaleWF(-19.500*FAdditionnalScale), ScaleHF(-5.000*FAdditionnalScale));
  end;

  GhostEyeLeft := TSprite.Create(texGhostEyeLeft, False);
  with GhostEyeLeft do begin
    SetChildOf(Self, 1);
    Frame := 1.0;
    SetSize(ScaleW(Round(39*FAdditionnalScale)), ScaleH(Round(19*FAdditionnalScale)));
    SetCoordinate(ScaleWF(-25.900*FAdditionnalScale), ScaleHF(-14.750*FAdditionnalScale));
  end;

  GhostEyeRight := TSprite.Create(texGhostEyeRight, False);
  with GhostEyeRight do begin
    SetChildOf(Self, 1);
    Frame := 1.0;
    SetSize(ScaleW(Round(39*FAdditionnalScale)), ScaleH(Round(19*FAdditionnalScale)));
    SetCoordinate(ScaleWF(-13.200*FAdditionnalScale), ScaleHF(-14.750*FAdditionnalScale));
  end;

  GhostEyeUp := TSprite.Create(texGhostEyeUp, False);
  with GhostEyeUp do begin
    SetChildOf(Self, 1);
    Frame := 1.0;
    SetSize(ScaleW(Round(39*FAdditionnalScale)), ScaleH(Round(19*FAdditionnalScale)));
    SetCoordinate(ScaleWF(-19.500*FAdditionnalScale), ScaleHF(-24.400*FAdditionnalScale));
  end;

  GhostMouthEye := TSprite.Create(texGhostMouthEye, False);
  with GhostMouthEye do begin
    SetChildOf(Self, 1);
    Frame := 1.0;
    SetSize(ScaleW(Round(46*FAdditionnalScale)), ScaleH(Round(24*FAdditionnalScale)));
    SetCoordinate(ScaleWF(-23.000*FAdditionnalScale), ScaleHF(-10.400*FAdditionnalScale));
  end;

  DressStretched := TSprite.Create(texGhostDressStretched, False);
  with DressStretched do begin
    SetChildOf(Self, -1);
    Frame := 1.0;
    SetSize(ScaleW(Round(64*FAdditionnalScale)), ScaleH(Round(64*FAdditionnalScale)));
    SetCoordinate(ScaleWF(-32.000*FAdditionnalScale), ScaleHF(-32.000*FAdditionnalScale));
  end;

  GhostLeg := TSprite.Create(texGhostLeg, False);
  with GhostLeg do begin
    SetChildOf(GhostBody, 0);
    Pivot := PointF(0.76, 0.61);
    Frame := 1.0;
    SetSize(ScaleW(Round(64*FAdditionnalScale)), ScaleH(Round(64*FAdditionnalScale)));
  end;

  DressRepear := TSprite.Create(texGhostDressRepear, False);
  with DressRepear do begin
    SetChildOf(GhostBody, 2);
    Frame := 1.0;
    SetSize(ScaleW(Round(64*FAdditionnalScale)), ScaleH(Round(64*FAdditionnalScale)));
  end;

end;

end.
